name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew :timeline:codeCoverageReport --stacktrace

      - name: Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./contentview/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml

      - name: Upload reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: contentview/build/reports/

      - name: Upload tests
        uses: actions/upload-artifact@v1
        with:
          name: tests
          path: contentview/build/test-results/

  publish:
    name: Publish library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Update version
        run: git fetch --tags && echo version=$(git tag | tail -1) > version.properties

      - name: Build library
        run: bash ./gradlew incrementVersion timeline:assembleRelease timeline:javadocJar --stacktrace

      - name: Get version
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ./version.properties
          property: version

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.read_property.outputs.value }}
          prerelease: true
          title: v.${{ steps.read_property.outputs.value }}
          files: |
            LICENSE
            timeline/build/outputs/**/*.jar
            timeline/build/outputs/**/*.aar
            timeline/build/libs/**/*.jar

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: timeline/build/outputs/

      - name: Upload docs
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: timeline/build/libs/
